spring:
  rabbitmq:
    connection-timeout: 1s # 设置MQ的连接超时时间
    host: localhost         # 本地服务，不需要写 IP
    port: 5672              # RabbitMQ 默认端口
    virtual-host: /hmall    # 你自己创建的 vhost
    username: jack          # 你设置的用户名
    password: 123456        # 对应密码
    publisher-confirm-type: correlated # 开启publisher confirm机制，并设置confirm类型
    publisher-returns: true # 开启publisher return机制
    template:
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
        max-attempts: 3 # 最大重试次数

logging:
  level:
    org.example.config: DEBUG
