spring:
  rabbitmq:
    host: localhost         # 本地服务，不需要写 IP
    port: 5672              # RabbitMQ 默认端口
    virtual-host: /hmall    # 你自己创建的 vhost
    username: jack          # 你设置的用户名
    password: 123456        # 对应密码
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000ms # 初识的失败等待时长为1秒
          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 # 最大重试次数
          stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false
